Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -97,7 +97,7 @@ jobs:
             --applicationId cf7ea4d3-743b-4b47-9575-a01d49169be6 \
             --clientSecret "FBI8Q~h03tyVq77yob_zpK4Mn0M-iGK5gKYW-cCl"
 
-      # Retry import solution
+           # Retry import solution
       - name: Retry Import Solution
         run: |
           for i in {1..3}; do
@@ -107,12 +107,26 @@ jobs:
                 --path "PAutomationGitTesting_1_0_0_3.zip" \
                 --environment 8c75c40e-a5b3-e306-a0e5-9116c62957d7 \
                 --overwrite-unmanaged-customizations true \
-                --log "import.log" && break || sleep 10
+                --log "import.log" \
+                --verbose > pac_import_output.log 2>&1 && break || sleep 10
             else
               echo "Error: PAutomationGitTesting_1_0_0_3.zip not found!"
               exit 1
             fi
           done
+
+      # Check if import.log exists and output content
+      - name: Display Import Logs
+        run: |
+          if [ -f "import.log" ]; then
+            echo "Import logs:"
+            cat import.log
+          else
+            echo "No import.log found. Checking pac_import_output.log for errors:"
+            cat pac_import_output.log
+            exit 1
+          fi
+
 
       # Check if import.log exists and output content
       - name: Display Import Logs
